### ISSUE TITLE
Map View under the bottom list.

### ISSUE THREAD

**Issue by developers-pio** [Karthik-B-06/RNOverlappingContainers#1]
When we overlap the bottom list on Map View. We could not access Map, it looks like an image and we want to access the Map view. Could you please suggest how to access Map view?

**Comment by Karthik-B-06** [comment]
Hey @developers-pio ... This example is a simple solution to overlapping containers that involve simple components like View, Image, and ScrollView. Having a MapView is a slightly bit complex wherein you can use a bottom-sheet. I came across a good library, check this out -> https://github.com/gorhom/react-native-bottom-sheet.

**Comment by Karthik-B-06** [comment]
Closing this issue. Feel free to reopen it.
